module.exports = {

	AddToChart_BlouseButton: '#email',
	ProceedToCheckout: '#password',
	ProceedGreen: '#login',
	SingInButton: '.menu > :nth-child(3) > a',
	SingOutButton: '.button_link',
	EmailAddress: '#name',
	CreateAccountButton: '#startDate',
	MrCheck: ':nth-child(3) > :nth-child(3) > .ui-state-default',
	// FirstName: '#customer_firstname',
	// LastName: '#customer_lastname',
	// Password: '#passwd',
	// Days: '#days',
	// Month: '#months',
	// Years: '#years',
	// NewsletterCheck: '#newsletter',
	// SpecialOffersCheck: '#optin',
	// Address: '#address1',
	// City: '#city',
	// State: '#id_state',
	// PostCode: '#postcode',
	// MobilePhone: '#phone_mobile',
	// Register: '#submitAccount > span',
	// AgreeTermsCheck: '#cgv',
	// PayByBankWireButton: '.bankwire',
	// ConfirmOrderButton: '#cart_navigation > .button > span',
	// OrderSuccessText: '.cheque-indent > .dark',
	// PostCodeErrorText: 'ol > li',
	
};