module.exports = {
	AddToChart_BlouseButton: '#homefeatured > :nth-child(2) > .product-container > .right-block > .button-container > .ajax_add_to_cart_button > span',
	ProceedToCheckout: '.button-medium > span',
	ProceedGreen: '.cart_navigation > .button > span',
	EmailAddress: '#email_create',
	CreateAccountButton: '#SubmitCreate > span',
	MrCheck: '#id_gender1',
	FirstName: '#customer_firstname',
	LastName: '#customer_lastname',
	Password: '#passwd',
	Days: '#days',
	Month: '#months',
	Years: '#years',
	NewsletterCheck: '#newsletter',
	SpecialOffersCheck: '#optin',
	Address: '#address1',
	City: '#city',
	State: '#id_state',
	PostCode: '#postcode',
	MobilePhone: '#phone_mobile',
	Register: '#submitAccount > span',
	AgreeTermsCheck: '#cgv',
	PayByBankWireButton: '.bankwire',
	ConfirmOrderButton: '#cart_navigation > .button > span',
	OrderSuccessText: '.cheque-indent > .dark',
	
};